#!/bin/bash

RED="\033[1;31m"
GREEN="\033[1;32m"
BLACK="\033[035m"
CYAN="\033[0;36m"
VIOLET="\033[0;30m"
NC="\033[0m"
NOPE="${RED}[nope]${NC}"
OK="${GREEN}[OK]✨${NC}"
TEST_NBR=18

FOLDER="minishell_tester/"
DESC=()
T_FOLDER=()
i=1
while [ $i -le $TEST_NBR ]
do
	DESC[$i]="test$i"
	T_FOLDER[$i]="${FOLDER}test$i/"
	(( i++ ))
done

remove_files()
{
	j=1
	t_nbr=$1
	f_nbr=$2
	while [ $j -le $f_nbr ]
	do
		rm -f ${T_FOLDER[$t_nbr]}outfile$j ${T_FOLDER[$t_nbr]}test$j ${T_FOLDER[$t_nbr]}diff
		(( j++ ))
	done
}

save_result()
{
	t_nbr=$1
	f_nbr=$2
	./minishell $t_nbr
	if diff -a ${T_FOLDER[$t_nbr]}outfile$f_nbr ${T_FOLDER[$t_nbr]}test$f_nbr > ${T_FOLDER[$t_nbr]}diff ; then
		TEST[$t_nbr]="${DESC[$t_nbr]} ${GREEN}${OK}${NC}\\n"
	else 
		TEST[$t_nbr]="${DESC[$t_nbr]} ${RED}${NOPE}${NC}\\n"
	fi
}

# 1. export something=blue | env >outfile1
# 2. << heredoc1 <<heredoc2 grep yo >outfile2 >outfile3
# 3. <infile1 <<heredoc1 grep yo >outfile4 | <infile2 grep file >outfile5
# 4. cat | cat | ls
# 5. export something=blue;env >outfile1
# 6. export something=;env >outfile1;export >outfile2;unset something; export >outfile3
# 7. export something=====blue;env outfile1;
# 8. echo -nnn -----nn --nnnnn >outfile1
# 9. env env env
# 10. env env hoi
# 11. unset PWD; env | grep PWD >outfile1
# 12. /bin/cd ../;pwd
# 16. export > outfile1

cd .. 
make

while getopts "de123456789abcfgh" opt; do
	case $opt in
		d)
			DESC[1]="${DESC[1]}: ${VIOLET}(${BLACK}export something=blue${VIOLET} | ${BLACK}env ${VIOLET}>outfile1):${NC}\\n"
			DESC[2]="${DESC[2]}: ${VIOLET}(<infile1 <infile2 ${BLACK}grep yo ${VIOLET}>outfile2 >outfile3):${NC}\\n"
			DESC[3]="${DESC[3]}: ${VIOLET}(<infile1 <infile2 ${BLACK}grep yo ${VIOLET}>outfile1 | <infile3 ${BLACK}grep file ${VIOLET}>outfile2):${NC}\\n"
			DESC[4]="${DESC[4]}: ${VIOLET}(${BLACK}cat ${VIOLET}| ${BLACK}cat${VIOLET} | ${BLACK}ls ${VIOLET}>outfile6):${NC}\\n"
			DESC[5]="${DESC[5]}: ${VIOLET}(${BLACK}export something=blue; env ${VIOLET}>outfile1)${NC}\\n"
			DESC[6]="${DESC[6]}: ${VIOLET}(${BLACK}export something=;env ${VIOLET}>outfile1 ${BLACK};export ${VIOLET}>outfile2;${BLACK}unset something; export ${VIOLET}>outfile3):${NC}\\n"
			DESC[7]="${DESC[7]}: ${VIOLET}(${BLACK}export something=====blue;env ${VIOLET}>outfile1;):${NC}\\n"
			DESC[8]="${DESC[8]}: ${VIOLET}(${BLACK}echo -nnn -----nn --nnnnn ${VIOLET}>outfile1):${NC}\\n"
			DESC[9]="${DESC[9]}: ${VIOLET}(${BLACK}env env env ${VIOLET}>outfile1):${NC}\\n"
			DESC[10]="${DESC[10]}: ${VIOLET}(${BLACK}env env hoi ${VIOLET}>outfile1):${NC}\\n"
			DESC[11]="${DESC[11]}: ${VIOLET}(${BLACK}unset PWD; env | grep PWD ${VIOLET}>outfile1):${NC}\\n"
			DESC[12]="${DESC[12]}: ${VIOLET}(${BLACK}/bin/cd ../;pwd ${VIOLET}>outfile1):${NC}\\n"
			DESC[16]="${DESC[16]}: ${VIOLET}(${BLACK}export${VIOLET}>outfile1):${NC}\\n"
			DESC[17]="${DESC[17]}: ${VIOLET}(${BLACK}export${VIOLET}>outfile1; ${BLACK}export${VIOLET}>outfile1):${NC}\\n"
			DESC[18]="${DESC[18]}: ${VIOLET}(${BLACK}export something=blue hallo yo= somethingggg=bbblue hdsrtghsrdghs=ugood? something=red hoi; export ${VIOLET}>outfile1)${NC}\\n"
			;;
		e)
			i=1
			while [ $i -le $TEST_NBR ]
			do
				echo -e "${DESC[$i]}" | awk '/./'
				(( i++ ))
			done
			;;
		1)
			t_nbr=1
			f_nbr=1
			remove_files $t_nbr $f_nbr
			export something=blue | env >${T_FOLDER[$t_nbr]}test1
			save_result $t_nbr $f_nbr
			;;
		2)
			t_nbr=2
			f_nbr=2
			remove_files $t_nbr $f_nbr
			echo "yooo: ${FOLDER}infile1 pwd: ${PWD}"
			< ${FOLDER}infile1 < ${FOLDER}infile2 grep yo >${T_FOLDER[$t_nbr]}test1 >${T_FOLDER[$t_nbr]}test2
			save_result $t_nbr $f_nbr
			;;
		3)
			t_nbr=3
			f_nbr=2
			remove_files $t_nbr $f_nbr
			< ${FOLDER}infile1 < ${FOLDER}infile2 grep yo >${T_FOLDER[$t_nbr]}test1 | < infile3 grep file >${T_FOLDER[$t_nbr]}test2
			save_result $t_nbr $f_nbr
			;;
		4)
			t_nbr=4
			f_nbr=1
			remove_files $t_nbr $f_nbr
			cat | cat | ls >${T_FOLDER[$t_nbr]}test1
			save_result $t_nbr $f_nbr
			;;
		5) 
			t_nbr=5
			f_nbr=1
			remove_files $t_nbr $f_nbr
			unset something
			export something=blue ;env >${T_FOLDER[$t_nbr]}test1
			save_result $t_nbr $f_nbr
			echo ${PWD}
			;;
		6)
			t_nbr=6
			f_nbr=3
			remove_files $t_nbr $f_nbr
			export something=;env >${T_FOLDER[$t_nbr]}test1;export >${T_FOLDER[$t_nbr]}test2;unset something; export >${T_FOLDER[$t_nbr]}test3
			save_result $t_nbr $f_nbr
			;;
		7)
			t_nbr=7
			f_nbr=1
			remove_files $t_nbr $f_nbr
			export something=====blue;env >${T_FOLDER[$t_nbr]}test1;
			save_result $t_nbr $f_nbr
			;;
		8)
			t_nbr=8
			f_nbr=1
			remove_files $t_nbr $f_nbr
			echo -nnn -----nn --nnnnn > ${T_FOLDER[$t_nbr]}test1
			save_result $t_nbr $f_nbr
			;;
		9)
			t_nbr=9
			f_nbr=1
			remove_files $t_nbr $f_nbr
			 env env env > ${T_FOLDER[$t_nbr]}test1
			save_result $t_nbr $f_nbr
			;;
		a)
			t_nbr=10
			f_nbr=1
			remove_files $t_nbr $f_nbr
			env env hoi > ${T_FOLDER[$t_nbr]}test1
			save_result $t_nbr $f_nbr
			;;
		b)
			t_nbr=11
			f_nbr=1
			# remove_files $t_nbr $f_nbr
			# $(bash unset XPC_FLAGS; (env | grep XPC > ${T_FOLDER[$t_nbr]}test1))
			rm -f ${T_FOLDER[$t_nbr]}outfile1 ${T_FOLDER[$t_nbr]}diff
			save_result $t_nbr $f_nbr
			;;
		c)
			t_nbr=12
			f_nbr=1
			remove_files $t_nbr $f_nbr
			usr/bin/cd ../;pwd > ${T_FOLDER[$t_nbr]}test1
			save_result $t_nbr $f_nbr
			;;
		f) 
			t_nbr=16
			f_nbr=1
			remove_files $t_nbr $f_nbr
			export > ${T_FOLDER[$t_nbr]}test1
			save_result $t_nbr $f_nbr
			;;
		g)
			t_nbr=17
			f_nbr=2
			remove_files $t_nbr $f_nbr
			export > ${T_FOLDER[$t_nbr]}test1; export > ${T_FOLDER[$t_nbr]}test2
			save_result $t_nbr $f_nbr
			;;
		h)
			t_nbr=18
			f_nbr=1
			remove_files $t_nbr $f_nbr
			export something=blue hallo yo= somethingggg=bbblue hdsrtghsrdghs=ugood? something=red hoi;export >${T_FOLDER[$t_nbr]}test1
			save_result $t_nbr $f_nbr
			;;
	esac
done
i=1
while [ $i -le $TEST_NBR ]
do
	echo -e "${TEST[$i]}" | awk '/./'
	(( i++ ))
done

# Hanging: 4 6 c